FROM node:12.13-alpine As development

WORKDIR /usr/src/app

ADD package*.json ./

ADD . .

RUN yarn run build

FROM node:12.13-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

ADD package*.json ./


ADD . .

COPY --from=development /usr/src/app/dist ./dist

EXPOSE 8080

CMD ["node", "dist/main"]